### ISSUE TITLE
[Request] Add missing Ennemie components 

### ISSUE THREAD

**Issue by YPhilou** [Kuma-Boo/project-reignition#144]
**Describe the limitation**
-
Some Ennemies don't have a proper Idle animation time 
the Ennemies don't have a disappear and reappear spawn option/delay  in the editor 

**Describe the new feature and it's purpose**
///////

**Mockup**
-
Reference in game DJ-PerfectAct secretRings the original

**Comment by Kuma-Boo** [comment]
Added in the main branch ^^
