### ISSUE TITLE
[Request] Improve cutscene quality

### ISSUE THREAD

**Issue by Kuma-Boo** [Kuma-Boo/project-reignition#73]
**Describe the limitation**
-

Something happened during the conversion process that caused cutscenes to look extremely low quality. This should be fixed.
Ideally, the CGI scenes (the opening and ending) should also be upscaled in some way.

**Comment by the-outcaster** [comment]
I can look into this by upscaling the videos with AI.

**Comment by Kuma-Boo** [comment]
Closed as upscaling cutscenes should really be for a final story release milestone, not SAGE.
