### ISSUE TITLE
[Request] Add customizable turning sensitivity

### ISSUE THREAD

**Issue by Kuma-Boo** [Kuma-Boo/project-reignition#93]
**Describe the limitation**
-

A major issue many players seem to have is the controls being "too touchy."

**Describe the new feature and it's purpose**
-

Adding a "controller sensitivity" option can allow players to customize their own experience to their own needs.

**Mockup**
-

**Comment by Kuma-Boo** [comment]
This isn't as necessary anymore, since we've figured out how to tune the controls.

**Comment by Kuma-Boo** [comment]
Turning options have been added in the skills menu.

**Comment by TheGershon** [comment]
I implore you to consider reopening this. While the 'Axis Dead Zone' option affects the inner deadzone of the analog stick, the real problem that I and I think many people have is that there's too much sensitivity between holding the stick perfectly straight up and tilting towards a diagonal, making it essentially impossible to move straight forward without going towards a side. I suggest a slight cross-shaped deadzone for the cardinal directions before left/right (for up and down) or up/down (for left and right) inputs begin to apply.

**Comment by Kuma-Boo** [comment]
I made them skills for a few reasons:
1. They were skills in the original game.
2. They work closely with the Speed-Up skills, as how fast you're moving will influence how sensitive you want the controls to be.
3. The Controls Test isn't a great place to tune the sensitivity due to it's camera perspective and how much you can move sideways. It simulates the more open areas (like Sand Oasis's field) rather than hallways (Sand Oasis's opening). I suppose we could change how the Controls Test works, although we would need to discuss it with the team.
4. Because of point 3, it's faster to change it before each level rather than going all the way back to the options menu.
5. Different save files might want different sensitivity configurations.

I'll see if we can update the controls to prevent drifting sideways though.
