### ISSUE TITLE
[BUG] Controller not reading

### ISSUE THREAD

**Issue by Kuma-Boo** [Kuma-Boo/project-reignition#97]
**Bug Description**

It's possible to get controllers to stop working?
Restarting the computer seems to fix the issue, so I won't be prioritizing this bug for now.

https://github.com/Kuma-Boo/project-reignition/assets/46894189/79af2a24-7d61-49cc-975b-6666d710c676

**Reproduction Steps**

Unknown

**System Information**

Game Version: v0.0.3

OS/Platform: N/A

**Comment by dreamsyntax** [comment]
Going by the Player LED, the controller entered Enhanced Mode. If the game was running and initially bound 'controller1' as the DualSense controller prior to Enhanced Mode, this would explain the bug.

Flow:
1. Controller is not in enhanced mode (Player LED probably off)
2. Playing the game for a while
3. Something triggers the controller to enter Enhanced Mode (examples: Steam, any other program that uses SDL)
4. Now the game has the old handle as controller1, and the newly detected "Enhanced Mode" controller as controller2.
